fullnameOverride:

metadata:
  namespace:

config:
  dbHost:
  dbPort:
  dbUsername: 
  dbPassword: 
  dbName: 
  dscpApiHost:
  dscpApiPort: 
  idServiceHost:
  idServicePort:
  inteliApiHost:
  inteliApiPort:
  inteliApiAudience:
  inteliApiGrant:
  inteliApiTokenAddr:
  fetchGcpKey:

image:
  repository: ghcr.io/inteli-poc/dscp-chain-watcher
  pullPolicy: IfNotPresent
  tag: 'v1.0.2'
  pullSecrets: 

vault:
  alpineutils:
  address:
  secretprefix:
  serviceaccountname:
  role:
  authpath:
